# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mult_bxxc <- function(a, b, c) {
    invisible(.Call(`_multbxxc_mult_bxxc`, a, b, c))
}

solve_ieu <- function(invdt, x0_, M, ali, s, ilua) {
    invisible(.Call(`_multbxxc_solve_ieu`, invdt, x0_, M, ali, s, ilua))
}

match_ij <- function(ix, jx, ti, tj) {
    .Call(`_multbxxc_match_ij`, ix, jx, ti, tj)
}

bop <- function(dst, mv, sop, src) {
    invisible(.Call(`_multbxxc_bop`, dst, mv, sop, src))
}

redim <- function(x, di) {
    invisible(.Call(`_multbxxc_redim`, x, di))
}

resize <- function(x_, di) {
    invisible(.Call(`_multbxxc_resize`, x_, di))
}

ij2ijv_i <- function(ir, jc) {
    .Call(`_multbxxc_ij2ijv_i`, ir, jc)
}

iv2v <- function(iv, v) {
    .Call(`_multbxxc_iv2v`, iv, v)
}

mm_xpf <- function(x, y_, lsel) {
    .Call(`_multbxxc_mm_xpf`, x, y_, lsel)
}

jrhs_ff <- function(jrhs, ff, xpfw) {
    invisible(.Call(`_multbxxc_jrhs_ff`, jrhs, ff, xpfw))
}

